name: Release App

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-apps:
    uses: ./.github/workflows/build_apps.yml
    name: Build Apps
    secrets: inherit
    with:
      build-windows-installer: true
      build-windows-portable: true
      build-python312-zipapp: true
      build-python313-zipapp: true
  release:
    name: Release
    needs: build-apps
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Packages
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Release Upload Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
            *_portable.zip \
            *_setup.exe \
            *_zipapp.pyzw \
            --clobber --repo $GITHUB_REPOSITORY
